server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - path=/api/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - path=/api/hotel/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - path=/api/ratings/**

eureka:
  instance:
  prefer-id-address: ture
  client.fetch-registry: true
  register-with-eureka: ture
  service-url.defaultZone: http://localhost:8761/eureka
