#spring:
#  datasourse:
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: viv123
#    driver-class: com.mysql.cj-jdbc.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: update
#        show-sql: true
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.MySQL8Dialect
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: ture
#      service-url:
#        defaultZone: http://localhost:8761/eureka
